### ISSUE TITLE
What is the purpose of the ".env.example" document?

### ISSUE THREAD

**Issue by jadenovalight** [Boierul/openai_chat_webapp#1]
Hello, I really don't understand about that document, I filled OPENAI_API_KEY with my own openai api key, but when I went to openai website to check if it had some changes, I found that the last used of my key was NEVER, it's strange, but the program is working, I can chat with a machine I guess, so, is there something wrong with what I did before?

**Comment by Boierul** [comment]
> Hello, I really don't understand about that document, I filled OPENAI_API_KEY with my own openai api key, but when I went to openai website to check if it had some changes, I found that the last used of my key was NEVER, it's strange, but the program is working, I can chat with a machine I guess, so, is there something wrong with what I did before?

Hey @yatuesday, glad that you checked my code. You did nothing wrong my friend, I've noticed it as well that the date-time of my API key is set to ( Last Used: Never ), even though is used in the production cloud application. Nevertheless, the API endpoints return the correct response and that is good enough for me. Cheers.
